
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.0'

_lr_method = 'LALR'

_lr_signature = 978852400
    
_lr_action_items = {'INCLUDE':([0,],[2,]),'FILENAME':([2,],[4,]),'CATCHALL':([0,],[3,]),'$end':([1,3,4,],[0,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> INCLUDE FILENAME','line',2,'p_include_line','maker.py',43),
  ('line -> CATCHALL','line',1,'p_catchall','maker.py',47),
]
