var data = {
  nodes:[
    {nodeName:"Soha Hassoun", is_person:1},
    {nodeName:"Matthias Scheutz", is_person:1},
    {nodeName:"Roni Khardon", is_person:1},
    {nodeName:"Robert Jacob", is_person:1},
    {nodeName:"Remco Chang", is_person:1},
    {nodeName:"Donna Slonim", is_person:1},
    {nodeName:"Carla Brodley", is_person:1},
    {nodeName:"Anselm Blumer", is_person:1},
    {nodeName:"Lenore Cowen", is_person:1},
    {nodeName:"Benjamin Hescott", is_person:1},
    {nodeName:"Ethan Danahy", is_person:1},
    {nodeName:"Sara Su", is_person:1},
    {nodeName:"Samuel Guyer", is_person:1},
    {nodeName:"Diane Souvaine", is_person:1},
    {nodeName:"Alva Couch", is_person:1},
    {nodeName:"Godfried Toussaint", is_person:1},
    {nodeName:"Norman Ramsey", is_person:1},
    {nodeName:"Eric Miller", is_person:1},
    {nodeName:"Chemical and Biological Engineering", is_person:0},
    {nodeName:"Psychology", is_person:0},
    {nodeName:"Finance/Economics", is_person:0},
    {nodeName:"Political Science", is_person:0},
    {nodeName:"Architecture", is_person:0},
    {nodeName:"Geography", is_person:0},
    {nodeName:"Cognitive Science", is_person:0},
    {nodeName:"Transportation", is_person:0},
    {nodeName:"Biomechanics", is_person:0},
    {nodeName:"Biomedical Engineering", is_person:0},
    {nodeName:"Tufts Medical Center", is_person:0},
    {nodeName:"ECE", is_person:0},
    {nodeName:"Chemistry", is_person:0},
    {nodeName:"Astrophysics", is_person:0},
    {nodeName:"Physics", is_person:0},
    {nodeName:"Child Development", is_person:0},
    {nodeName:"Mechanical Engineering", is_person:0},
    {nodeName:"Tufts UIT", is_person:0},
    {nodeName:"Mathematics", is_person:0},
    {nodeName:"Civil and Environmental Engineering", is_person:0},
    {nodeName:"Center for Engineering Education and Outreach", is_person:0},
    {nodeName:"Human Factors Engineering", is_person:0},
    {nodeName:"Education", is_person:0},
    {nodeName:"Molecular Biology", is_person:0},
  ],
  links:[
    {source:1, target:2, person_person_link:true},
    {source:1, target:3, person_person_link:true},
    {source:4, target:3, person_person_link:true},
    {source:4, target:1, person_person_link:true},
    {source:5, target:6, person_person_link:true},
    {source:5, target:7, person_person_link:true},
    {source:5, target:8, person_person_link:true},
    {source:5, target:9, person_person_link:true},
    {source:2, target:6, person_person_link:true},
    {source:6, target:7, person_person_link:true},
    {source:3, target:10, person_person_link:true},
    {source:3, target:11, person_person_link:true},
    {source:3, target:8, person_person_link:true},
    {source:11, target:4, person_person_link:true},
    {source:11, target:8, person_person_link:true},
    {source:11, target:12, person_person_link:true},
    {source:13, target:9, person_person_link:true},
    {source:14, target:4, person_person_link:true},
    {source:15, target:13, person_person_link:true},
    {source:7, target:8, person_person_link:true},
    {source:7, target:9, person_person_link:true},
    {source:7, target:2, person_person_link:true},
    {source:16, target:9, person_person_link:true},
    {source:17, target:2, person_person_link:true},
    {source:0, target:18, person_person_link:false},
    {source:1, target:19, person_person_link:false},
    {source:4, target:20, person_person_link:false},
    {source:4, target:21, person_person_link:false},
    {source:4, target:22, person_person_link:false},
    {source:4, target:23, person_person_link:false},
    {source:4, target:24, person_person_link:false},
    {source:4, target:25, person_person_link:false},
    {source:4, target:26, person_person_link:false},
    {source:5, target:27, person_person_link:false},
    {source:5, target:28, person_person_link:false},
    {source:2, target:29, person_person_link:false},
    {source:2, target:30, person_person_link:false},
    {source:2, target:28, person_person_link:false},
    {source:2, target:31, person_person_link:false},
    {source:6, target:30, person_person_link:false},
    {source:6, target:32, person_person_link:false},
    {source:6, target:28, person_person_link:false},
    {source:6, target:23, person_person_link:false},
    {source:6, target:31, person_person_link:false},
    {source:3, target:33, person_person_link:false},
    {source:3, target:27, person_person_link:false},
    {source:3, target:19, person_person_link:false},
    {source:3, target:34, person_person_link:false},
    {source:11, target:35, person_person_link:false},
    {source:13, target:36, person_person_link:false},
    {source:13, target:18, person_person_link:false},
    {source:14, target:37, person_person_link:false},
    {source:7, target:24, person_person_link:false},
    {source:16, target:38, person_person_link:false},
    {source:10, target:38, person_person_link:false},
    {source:10, target:34, person_person_link:false},
    {source:10, target:39, person_person_link:false},
    {source:10, target:40, person_person_link:false},
    {source:17, target:27, person_person_link:false},
    {source:17, target:37, person_person_link:false},
    {source:17, target:28, person_person_link:false},
    {source:17, target:41, person_person_link:false},
  ]
};
