
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = '4\x10\xaaq\xae\xdb\xd1[\x13\x11\xc7\x19\xd3E\x8c\\'

_lr_action_items = {'STRING':([3,],[4,]),'NUMBER':([3,7,9,],[5,8,10,]),'BOOLEAN':([3,],[6,]),'COMMA':([5,8,],[7,9,]),'VARIABLE':([0,],[2,]),'ASSIGN':([2,],[3,]),'$end':([1,4,5,6,10,],[0,-4,-1,-3,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assignment':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('assignment',3,'p_assign_value','schedule.py',96),
  ('assignment',7,'p_assign_value','schedule.py',97),
  ('assignment',3,'p_assign_value','schedule.py',98),
  ('assignment',3,'p_assign_value','schedule.py',99),
  ('timeblock',5,'p_timeblock','schedule.py',107),
  ('classinfo',6,'p_classinfo','schedule.py',115),
  ('class',2,'p_class','schedule.py',123),
  ('class',4,'p_class','schedule.py',124),
  ('class',6,'p_class','schedule.py',125),
  ('class',8,'p_class','schedule.py',126),
  ('class',10,'p_class','schedule.py',127),
]
